# Generated by Django 3.2 on 2021-04-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='desc2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
